=== Luita7/Melola_LM-04-2023-24/ejercicios/Ejercio1/ejercicioReutilizable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <!-- TIPOS COMPLEJOS REUTILIZABLES-->
    <xs:complexType name="tipoContacto">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="calle" type="xs:string" />
            <xs:element name="ciudad" type="xs:string" />
            <xs:element name="pais" type="xs:string" />
            <xs:element name="codigo" minOccurs="0" type="xs:string" />
            <xs:element name="vip" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoAgenda">
        <xs:sequence>
            <xs:element name="contacto" maxOccurs="unbounded" type="tipoContacto" />
        </xs:sequence>
    </xs:complexType>


    <!-- ROOT -->
    <xs:element name="agenda" type="tipoAgenda" />

</xs:schema>

=== Luita7/Melola_LM-04-2023-24/ejercicios/Ejercio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, calle, ciudad, pais, codigo?, vip?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT vip EMPTY>
]>
-->
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicioReutilizable.xsd">
    <contacto>
        <nombre>Pepe García</nombre>
        <calle>C/Ronda, 3</calle>
        <ciudad>Moncófar</ciudad>
        <pais>España</pais>
        <codigo>18465</codigo>
        <vip />
    </contacto>
    <contacto>
        <nombre>Lola García</nombre>
        <calle>C/Paraiso, 5</calle>
        <ciudad>Ciudad Real</ciudad>
        <pais>España</pais>
    </contacto>
    <contacto>
        <nombre>Lola García</nombre>
        <calle>C/Paraiso, 5</calle>
        <ciudad>Ciudad Real</ciudad>
        <pais>España</pais>
    </contacto>
</agenda>
